name: "modbus-proxy"
description: "Proxy for Accessing three modbus systems."
version: "1.0.0"
slug: "modbus_proxy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
url: "https://github.com/uk05de/ha-modbusproxy"
startup: services
init: false
options:
  upstreamhost: "192.168.178.100"
  upstreamport: 502
  listenport: 502
  connection_time: 0.1
  timeout: 10
  filter: []
  enablehost2: true
  upstreamhost2: "192.168.178.101"
  upstreamport2: 502
  listenport2: 503
  connection_time2: 0.1
  timeout2: 10
  filter2: []
  enablehost3: true
  upstreamhost3: "192.168.178.102"
  upstreamport3: 502
  listenport3: 504
  connection_time3: 0.1
  timeout3: 10
  filter3: []
  loglevel: "INFO"
schema:
  upstreamhost: str
  upstreamport: int
  listenport: int
  connection_time: float
  timeout: int
  filter:
    - slave: int
      function: int
      address_start: int
      address_end: int
  enablehost2: bool
  upstreamhost2: str
  upstreamport2: int
  listenport2: int
  connection_time2: float
  timeout2: int
  filter2:
    - slave: int
      function: int
      address_start: int
      address_end: int
  enablehost3: bool
  upstreamhost3: str
  upstreamport3: int
  listenport3: int
  connection_time3: float
  timeout3: int
  filter3:
    - slave: int
      function: int
      address_start: int
      address_end: int
  loglevel: list(INFO|DEBUG|ERROR)
ports:
  502/tcp: 502
  503/tcp: 503
  504/tcp: 504
